BATCH_SIZE = 256
NUM_SAMPLES = 100
NUM_DEEP_ENSEMBLE_ESTIMATORS = 10

TEST_MODE = True

FIGURE_FOLDER = './figures'
DATA_FOLDER = './results_data'

NUM_LABEL_NOISE_STEPS = 20
NUM_DECREASING_DATASET_STEPS = 20


if TEST_MODE:
    NUM_SAMPLES = 3
    NUM_DEEP_ENSEMBLE_ESTIMATORS = 2
    NUM_LABEL_NOISE_STEPS = 3
    NUM_DECREASING_DATASET_STEPS = 3
