import os

BATCH_SIZE = 256
NUM_SAMPLES = 100
NUM_DEEP_ENSEMBLE_ESTIMATORS = 10

TEST_MODE = True

FIGURE_FOLDER = './figures'
DATA_FOLDER = './results_data'

if TEST_MODE:
    NUM_SAMPLES = 3
    NUM_DEEP_ENSEMBLE_ESTIMATORS = 2
