BATCH_SIZE = 128
NUM_SAMPLES = 50
NUM_DEEP_ENSEMBLE_ESTIMATORS = 10

TEST_MODE = False

FIGURE_FOLDER = './figures'
DATA_FOLDER = './results_data'

NUM_LABEL_NOISE_STEPS = 10
NUM_DECREASING_DATASET_STEPS = 10

N_CIFAR10_TEST_SAMPLES = 1_000

MODEL_TRAIN_VERBOSE = 0

if TEST_MODE:
    NUM_SAMPLES = 3
    NUM_DEEP_ENSEMBLE_ESTIMATORS = 2
    NUM_LABEL_NOISE_STEPS = 3
    NUM_DECREASING_DATASET_STEPS = 3
